// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: crowdash

#ifndef _CROWDASH_UI_H
#define _CROWDASH_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////
#include "ui_screendashboard.h"
#include "ui_screentimer.h"
#include "ui_screenlogger.h"
#include "ui_screenschedule.h"

///////////////////// VARIABLES ////////////////////

// EVENTS
extern lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE( ui_img_snowrainmix_png);   // assets/SnowRainMix.png
LV_IMG_DECLARE( ui_img_rt_arrow_png);   // assets/rt_arrow.png
LV_IMG_DECLARE( ui_img_partlycloudy_png);   // assets/PartlyCloudy.png
LV_IMG_DECLARE( ui_img_heavyrain_png);   // assets/HeavyRain.png
LV_IMG_DECLARE( ui_img_sunnyday_png);   // assets/SunnyDay.png
LV_IMG_DECLARE( ui_img_thunderstorms_png);   // assets/Thunderstorms.png
LV_IMG_DECLARE( ui_img_lt_arrow_png);   // assets/lt_arrow.png

// FONTS
LV_FONT_DECLARE( ui_font_Big_Number);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
