// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: crowdash

#ifndef UI_SCREENSETUP_H
#define UI_SCREENSETUP_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_screensetup
extern void ui_screensetup_screen_init(void);
extern void ui_screensetup_screen_destroy(void);
extern lv_obj_t *ui_screensetup;
extern lv_obj_t *ui_kbSetupInput;
extern lv_obj_t *ui_btnSaveSettings;
extern lv_obj_t *ui_lblReset1;
extern lv_obj_t *ui_Spinbox1;
extern lv_obj_t *ui_pnlDisplaySchedule;
extern lv_obj_t *ui_txtSleepTime;
extern lv_obj_t *ui_swtScheduleEnable;
extern lv_obj_t *ui_Label4;
extern lv_obj_t *ui_Label5;
extern lv_obj_t *ui_lblDisplaySchedule;
extern lv_obj_t *ui_lblEnableSchedule;
extern lv_obj_t *ui_txtWakeTime;
extern lv_obj_t *ui_pnlWeather;
extern lv_obj_t *ui_txtZipCode;
extern lv_obj_t *ui_lblZipCode;
extern lv_obj_t *ui_lblWeather;
// CUSTOM VARIABLES
extern lv_obj_t *uic_screensetup;
extern lv_obj_t *uic_txtSleepTime;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

