// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: crowdash

#ifndef UI_SCREENTIMER_H
#define UI_SCREENTIMER_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_screentimer
extern void ui_screentimer_screen_init(void);
extern void ui_screentimer_screen_destroy(void);
extern lv_obj_t *ui_screentimer;
extern lv_obj_t *ui_kbNumberPad;
extern lv_obj_t *ui_btnStartTimer;
extern lv_obj_t *ui_lblStart;
extern lv_obj_t *ui_btnStopTimer;
extern lv_obj_t *ui_lblStop;
extern lv_obj_t *ui_btnResetTimer;
extern lv_obj_t *ui_lblReset;
extern lv_obj_t *ui_barTimer;
extern void ui_event_btnGoToTimers1( lv_event_t * e);
extern lv_obj_t *ui_btnGoToTimers1;
extern lv_obj_t *ui_Spinbox2;
extern lv_obj_t *ui_btnClearTimer;
extern lv_obj_t *ui_lblClear;
extern lv_obj_t *ui_txtTimeRemaining;
extern lv_obj_t *ui_pnlEnterTime;
extern lv_obj_t *ui_txtTimerStartValue;
extern lv_obj_t *ui_swtModeMinOrSec;
extern lv_obj_t *ui_Label3;
extern lv_obj_t *ui_Label2;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

