// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: crowdash

#ifndef UI_SCREENDASHBOARD_H
#define UI_SCREENDASHBOARD_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_screendashboard
extern void ui_screendashboard_screen_init(void);
extern void ui_screendashboard_screen_destroy(void);
extern lv_obj_t *ui_screendashboard;
extern lv_obj_t *ui_pnlTimeDate;
extern lv_obj_t *ui_lblTimeOfDay;
extern lv_obj_t *ui_lblDate;
extern lv_obj_t *ui_pnlWeatherD0;
extern lv_obj_t *ui_chtTemp;
extern lv_obj_t *ui_chtHumidity;
extern lv_obj_t *ui_lblTempD0;
extern lv_obj_t *ui_Label6;
extern lv_obj_t *ui_lblHumidityD0;
extern lv_obj_t *ui_pnlForecastD0;
extern lv_obj_t *ui_imgForecastD0;
extern lv_obj_t *ui_lblForecastRainChanceD0;
extern lv_obj_t *ui_lblForecastTempLoD0;
extern lv_obj_t *ui_lblForecastTempHiD0;
extern void ui_event_btnGoToTimerScreen( lv_event_t * e);
extern lv_obj_t *ui_btnGoToTimerScreen;
extern lv_obj_t *ui_pnlForecast;
extern lv_obj_t *ui_pnlForecastD1;
extern lv_obj_t *ui_imgForecastD1;
extern lv_obj_t *ui_lblForecastDayD1;
extern lv_obj_t *ui_lblForecastTempLoD1;
extern lv_obj_t *ui_lblForecastTempHiD1;
extern lv_obj_t *ui_sldTempRangeD1;
extern lv_obj_t *ui_lblForecastRainChanceD1;
extern lv_obj_t *ui_pnlForecastD2;
extern lv_obj_t *ui_imgForecastD2;
extern lv_obj_t *ui_lblForecastDayD2;
extern lv_obj_t *ui_lblForecastTempLoD2;
extern lv_obj_t *ui_lblForecastTempHiD2;
extern lv_obj_t *ui_sldTempRangeD2;
extern lv_obj_t *ui_lblForecastRainChanceD2;
extern lv_obj_t *ui_pnlForecastD3;
extern lv_obj_t *ui_imgForecastD3;
extern lv_obj_t *ui_lblForecastDayD3;
extern lv_obj_t *ui_lblForecastTempLoD3;
extern lv_obj_t *ui_lblForecastTempHiD3;
extern lv_obj_t *ui_sldTempRangeD3;
extern lv_obj_t *ui_lblForecastRainChanceD3;
extern lv_obj_t *ui_pnlForecastD4;
extern lv_obj_t *ui_imgForecastD4;
extern lv_obj_t *ui_lblForecastDayD4;
extern lv_obj_t *ui_lblForecastTempLoD4;
extern lv_obj_t *ui_lblForecastTempHiD4;
extern lv_obj_t *ui_sldTempRangeD4;
extern lv_obj_t *ui_lblForecastRainChanceD4;
extern lv_obj_t *ui_pnlForecastD5;
extern lv_obj_t *ui_imgForecastD5;
extern lv_obj_t *ui_lblForecastDayD5;
extern lv_obj_t *ui_lblForecastTempLoD5;
extern lv_obj_t *ui_lblForecastTempHiD5;
extern lv_obj_t *ui_sldTempRangeD5;
extern lv_obj_t *ui_lblForecastRainChanceD5;
extern lv_obj_t *ui_pnlStatus;
extern lv_obj_t *ui_pnlGarageDoorStatus;
extern lv_obj_t *ui_lblGarageDoor;
extern lv_obj_t *ui_lblGarageDoorStatus;
extern lv_obj_t *ui_pnlPlaceHolderStatus;
extern lv_obj_t *ui_lblEvent1;
extern lv_obj_t *ui_lblEventStatus1;
extern lv_obj_t *ui_pnlCalEvents;
extern lv_obj_t *ui_txtCalEvents;
extern lv_obj_t *ui_pnlEnclosure;
extern lv_obj_t *ui_Label9;
extern lv_obj_t *ui_lblEnclosureTemp;
extern lv_obj_t *ui_lblEnclosureHumidity;
extern lv_obj_t *ui_pnlIndoor;
extern lv_obj_t *ui_Label1;
extern lv_obj_t *ui_lblIndoorTemp;
extern lv_obj_t *ui_lblIndoorHumidity;
extern lv_obj_t *ui_lblTemp;
extern lv_obj_t *ui_lblHumidity;
extern lv_obj_t *ui_lblGarageTime;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

