// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: crowdash

#ifndef UI_SCREENLOGGER_H
#define UI_SCREENLOGGER_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_screenlogger
extern void ui_screenlogger_screen_init(void);
extern void ui_screenlogger_screen_destroy(void);
extern lv_obj_t *ui_screenlogger;
extern lv_obj_t *ui_txtLogger;
extern void ui_event_btnGoToTimerScreen2( lv_event_t * e);
extern lv_obj_t *ui_btnGoToTimerScreen2;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

