// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: crowdash

#include "ui.h"

lv_obj_t *uic_txtSleepTime;
lv_obj_t *uic_screensetup;
lv_obj_t *ui_screensetup = NULL;lv_obj_t *ui_kbSetupInput = NULL;lv_obj_t *ui_btnSaveSettings = NULL;lv_obj_t *ui_lblReset1 = NULL;lv_obj_t *ui_Spinbox1 = NULL;lv_obj_t *ui_pnlDisplaySchedule = NULL;lv_obj_t *ui_txtSleepTime = NULL;lv_obj_t *ui_swtScheduleEnable = NULL;lv_obj_t *ui_Label4 = NULL;lv_obj_t *ui_Label5 = NULL;lv_obj_t *ui_lblDisplaySchedule = NULL;lv_obj_t *ui_lblEnableSchedule = NULL;lv_obj_t *ui_txtWakeTime = NULL;lv_obj_t *ui_pnlWeather = NULL;lv_obj_t *ui_txtZipCode = NULL;lv_obj_t *ui_lblZipCode = NULL;lv_obj_t *ui_lblWeather = NULL;
// event funtions

// build funtions

void ui_screensetup_screen_init(void)
{
ui_screensetup = lv_obj_create(NULL);
lv_obj_clear_flag( ui_screensetup, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_kbSetupInput = lv_keyboard_create(ui_screensetup);
lv_keyboard_set_mode(ui_kbSetupInput,LV_KEYBOARD_MODE_NUMBER);
lv_obj_set_width( ui_kbSetupInput, 441);
lv_obj_set_height( ui_kbSetupInput, 452);
lv_obj_set_x( ui_kbSetupInput, 160 );
lv_obj_set_y( ui_kbSetupInput, -13 );
lv_obj_set_align( ui_kbSetupInput, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_kbSetupInput, LV_OBJ_FLAG_PRESS_LOCK );    /// Flags

lv_obj_set_style_text_font(ui_kbSetupInput, &lv_font_montserrat_48, LV_PART_ITEMS| LV_STATE_DEFAULT);

ui_btnSaveSettings = lv_btn_create(ui_screensetup);
lv_obj_set_width( ui_btnSaveSettings, 207);
lv_obj_set_height( ui_btnSaveSettings, 72);
lv_obj_set_x( ui_btnSaveSettings, -226 );
lv_obj_set_y( ui_btnSaveSettings, 194 );
lv_obj_set_align( ui_btnSaveSettings, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_btnSaveSettings, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_btnSaveSettings, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_btnSaveSettings, lv_color_hex(0x0C0D60), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_btnSaveSettings, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_btnSaveSettings, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_btnSaveSettings, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_btnSaveSettings, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_btnSaveSettings, &lv_font_montserrat_28, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lblReset1 = lv_label_create(ui_btnSaveSettings);
lv_obj_set_width( ui_lblReset1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_lblReset1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_lblReset1, 1 );
lv_obj_set_y( ui_lblReset1, -1 );
lv_obj_set_align( ui_lblReset1, LV_ALIGN_CENTER );
lv_label_set_text(ui_lblReset1,"Save");
lv_obj_set_style_text_align(ui_lblReset1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Spinbox1 = lv_spinbox_create(ui_screensetup);
lv_obj_set_width( ui_Spinbox1, 70);
lv_obj_set_height( ui_Spinbox1, 42);
lv_obj_set_x( ui_Spinbox1, -465 );
lv_obj_set_y( ui_Spinbox1, 422 );
lv_obj_set_align( ui_Spinbox1, LV_ALIGN_CENTER );
lv_spinbox_set_digit_format( ui_Spinbox1, 4, 2);
lv_spinbox_set_range( ui_Spinbox1, 0,9999 );
lv_spinbox_set_cursor_pos(ui_Spinbox1, 1 - 1);

ui_pnlDisplaySchedule = lv_obj_create(ui_screensetup);
lv_obj_set_width( ui_pnlDisplaySchedule, 312);
lv_obj_set_height( ui_pnlDisplaySchedule, 229);
lv_obj_set_x( ui_pnlDisplaySchedule, -226 );
lv_obj_set_y( ui_pnlDisplaySchedule, -115 );
lv_obj_set_align( ui_pnlDisplaySchedule, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_pnlDisplaySchedule, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_txtSleepTime = lv_textarea_create(ui_pnlDisplaySchedule);
lv_obj_set_width( ui_txtSleepTime, 132);
lv_obj_set_height( ui_txtSleepTime, LV_SIZE_CONTENT);   /// 75
lv_obj_set_x( ui_txtSleepTime, 81 );
lv_obj_set_y( ui_txtSleepTime, 17 );
lv_obj_set_align( ui_txtSleepTime, LV_ALIGN_CENTER );
lv_textarea_set_max_length(ui_txtSleepTime,4);
lv_textarea_set_text(ui_txtSleepTime,"2300");
lv_textarea_set_one_line(ui_txtSleepTime,true);
lv_obj_set_style_text_color(ui_txtSleepTime, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_txtSleepTime, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_txtSleepTime, &lv_font_montserrat_42, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_txtSleepTime, lv_color_hex(0x565252), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_txtSleepTime, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_txtSleepTime, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_txtSleepTime, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_txtSleepTime, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_txtSleepTime, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_swtScheduleEnable = lv_switch_create(ui_pnlDisplaySchedule);
lv_obj_set_width( ui_swtScheduleEnable, 90);
lv_obj_set_height( ui_swtScheduleEnable, 49);
lv_obj_set_x( ui_swtScheduleEnable, 106 );
lv_obj_set_y( ui_swtScheduleEnable, -47 );
lv_obj_set_align( ui_swtScheduleEnable, LV_ALIGN_CENTER );
lv_obj_set_style_bg_color(ui_swtScheduleEnable, lv_color_hex(0x525052), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_swtScheduleEnable, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label4 = lv_label_create(ui_pnlDisplaySchedule);
lv_obj_set_width( ui_Label4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label4, -43 );
lv_obj_set_y( ui_Label4, 17 );
lv_obj_set_align( ui_Label4, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label4,"Sleep at");
lv_obj_set_style_text_font(ui_Label4, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label5 = lv_label_create(ui_pnlDisplaySchedule);
lv_obj_set_width( ui_Label5, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label5, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label5, -45 );
lv_obj_set_y( ui_Label5, 76 );
lv_obj_set_align( ui_Label5, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label5,"Wake at");
lv_obj_set_style_text_font(ui_Label5, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lblDisplaySchedule = lv_label_create(ui_pnlDisplaySchedule);
lv_obj_set_width( ui_lblDisplaySchedule, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_lblDisplaySchedule, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_lblDisplaySchedule, -15 );
lv_obj_set_y( ui_lblDisplaySchedule, -94 );
lv_obj_set_align( ui_lblDisplaySchedule, LV_ALIGN_CENTER );
lv_label_set_text(ui_lblDisplaySchedule,"Display Schedule");
lv_obj_set_style_text_color(ui_lblDisplaySchedule, lv_color_hex(0x5DB520), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_lblDisplaySchedule, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_lblDisplaySchedule, &lv_font_montserrat_28, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lblEnableSchedule = lv_label_create(ui_pnlDisplaySchedule);
lv_obj_set_width( ui_lblEnableSchedule, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_lblEnableSchedule, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_lblEnableSchedule, -46 );
lv_obj_set_y( ui_lblEnableSchedule, -48 );
lv_obj_set_align( ui_lblEnableSchedule, LV_ALIGN_CENTER );
lv_label_set_text(ui_lblEnableSchedule,"Enable Schedule");
lv_obj_set_style_text_font(ui_lblEnableSchedule, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_txtWakeTime = lv_textarea_create(ui_pnlDisplaySchedule);
lv_obj_set_width( ui_txtWakeTime, 132);
lv_obj_set_height( ui_txtWakeTime, LV_SIZE_CONTENT);   /// 75
lv_obj_set_x( ui_txtWakeTime, 80 );
lv_obj_set_y( ui_txtWakeTime, 77 );
lv_obj_set_align( ui_txtWakeTime, LV_ALIGN_CENTER );
lv_textarea_set_max_length(ui_txtWakeTime,4);
lv_textarea_set_text(ui_txtWakeTime,"0700");
lv_textarea_set_one_line(ui_txtWakeTime,true);
lv_obj_set_style_text_color(ui_txtWakeTime, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_txtWakeTime, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_txtWakeTime, &lv_font_montserrat_42, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_txtWakeTime, lv_color_hex(0x565252), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_txtWakeTime, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_txtWakeTime, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_txtWakeTime, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_txtWakeTime, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_txtWakeTime, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_pnlWeather = lv_obj_create(ui_screensetup);
lv_obj_set_width( ui_pnlWeather, 312);
lv_obj_set_height( ui_pnlWeather, 98);
lv_obj_set_x( ui_pnlWeather, -225 );
lv_obj_set_y( ui_pnlWeather, 61 );
lv_obj_set_align( ui_pnlWeather, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_pnlWeather, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_txtZipCode = lv_textarea_create(ui_pnlWeather);
lv_obj_set_width( ui_txtZipCode, 154);
lv_obj_set_height( ui_txtZipCode, LV_SIZE_CONTENT);   /// 75
lv_obj_set_x( ui_txtZipCode, 67 );
lv_obj_set_y( ui_txtZipCode, 18 );
lv_obj_set_align( ui_txtZipCode, LV_ALIGN_CENTER );
lv_textarea_set_max_length(ui_txtZipCode,5);
lv_textarea_set_text(ui_txtZipCode,"78731");
lv_textarea_set_one_line(ui_txtZipCode,true);
lv_obj_set_style_text_color(ui_txtZipCode, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_txtZipCode, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_txtZipCode, &lv_font_montserrat_42, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_txtZipCode, lv_color_hex(0x565252), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_txtZipCode, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_txtZipCode, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_txtZipCode, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_txtZipCode, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_txtZipCode, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lblZipCode = lv_label_create(ui_pnlWeather);
lv_obj_set_width( ui_lblZipCode, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_lblZipCode, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_lblZipCode, -87 );
lv_obj_set_y( ui_lblZipCode, 20 );
lv_obj_set_align( ui_lblZipCode, LV_ALIGN_CENTER );
lv_label_set_text(ui_lblZipCode,"Zipcode");
lv_obj_set_style_text_font(ui_lblZipCode, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lblWeather = lv_label_create(ui_pnlWeather);
lv_obj_set_width( ui_lblWeather, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_lblWeather, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_lblWeather, -79 );
lv_obj_set_y( ui_lblWeather, -23 );
lv_obj_set_align( ui_lblWeather, LV_ALIGN_CENTER );
lv_label_set_text(ui_lblWeather,"Weather");
lv_obj_set_style_text_color(ui_lblWeather, lv_color_hex(0x5DB520), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_lblWeather, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_lblWeather, &lv_font_montserrat_28, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_keyboard_set_textarea(ui_kbSetupInput,ui_txtSleepTime);
uic_screensetup = ui_screensetup;
uic_txtSleepTime = ui_txtSleepTime;

}

void ui_screensetup_screen_destroy(void)
{
   if (ui_screensetup) lv_obj_del(ui_screensetup);

// NULL screen variables
uic_screensetup= NULL;
ui_screensetup= NULL;
ui_kbSetupInput= NULL;
ui_btnSaveSettings= NULL;
ui_lblReset1= NULL;
ui_Spinbox1= NULL;
ui_pnlDisplaySchedule= NULL;
uic_txtSleepTime= NULL;
ui_txtSleepTime= NULL;
ui_swtScheduleEnable= NULL;
ui_Label4= NULL;
ui_Label5= NULL;
ui_lblDisplaySchedule= NULL;
ui_lblEnableSchedule= NULL;
ui_txtWakeTime= NULL;
ui_pnlWeather= NULL;
ui_txtZipCode= NULL;
ui_lblZipCode= NULL;
ui_lblWeather= NULL;

}
