// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: crowdash

#include "ui.h"

lv_obj_t *ui_screenlogger = NULL;lv_obj_t *ui_txtLogger = NULL;lv_obj_t *ui_btnGoToTimerScreen2 = NULL;
// event funtions
void ui_event_btnGoToTimerScreen2( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_screentimer, LV_SCR_LOAD_ANIM_MOVE_LEFT, 100, 0, &ui_screentimer_screen_init);
}
}

// build funtions

void ui_screenlogger_screen_init(void)
{
ui_screenlogger = lv_obj_create(NULL);
lv_obj_clear_flag( ui_screenlogger, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_txtLogger = lv_textarea_create(ui_screenlogger);
lv_obj_set_width( ui_txtLogger, 693);
lv_obj_set_height( ui_txtLogger, 455);
lv_obj_set_x( ui_txtLogger, 35 );
lv_obj_set_y( ui_txtLogger, -5 );
lv_obj_set_align( ui_txtLogger, LV_ALIGN_CENTER );
lv_obj_set_style_text_font(ui_txtLogger, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_btnGoToTimerScreen2 = lv_imgbtn_create(ui_screenlogger);
lv_imgbtn_set_src(ui_btnGoToTimerScreen2, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_lt_arrow_png, NULL);
lv_imgbtn_set_src(ui_btnGoToTimerScreen2, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_lt_arrow_png, NULL);
lv_obj_set_width( ui_btnGoToTimerScreen2, 64);
lv_obj_set_height( ui_btnGoToTimerScreen2, 64);
lv_obj_set_x( ui_btnGoToTimerScreen2, -356 );
lv_obj_set_y( ui_btnGoToTimerScreen2, 194 );
lv_obj_set_align( ui_btnGoToTimerScreen2, LV_ALIGN_CENTER );
lv_obj_set_style_radius(ui_btnGoToTimerScreen2, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_btnGoToTimerScreen2, lv_color_hex(0x4D4F5B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_btnGoToTimerScreen2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_color(ui_btnGoToTimerScreen2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_outline_opa(ui_btnGoToTimerScreen2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_btnGoToTimerScreen2, ui_event_btnGoToTimerScreen2, LV_EVENT_ALL, NULL);

}

void ui_screenlogger_screen_destroy(void)
{
   if (ui_screenlogger) lv_obj_del(ui_screenlogger);

// NULL screen variables
ui_screenlogger= NULL;
ui_txtLogger= NULL;
ui_btnGoToTimerScreen2= NULL;

}
