// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: crowdash

#include "../ui.h"

lv_obj_t *ui_screendashboard = NULL;lv_obj_t *ui_pnlTimeDate = NULL;lv_obj_t *ui_lblTimeOfDay = NULL;lv_obj_t *ui_lblDate = NULL;lv_obj_t *ui_pnlOutsideTemp = NULL;lv_obj_t *ui_chtTemp = NULL;lv_obj_t *ui_chtHumidity = NULL;lv_obj_t *ui_lblCurrentTemp = NULL;lv_obj_t *ui_lblCurrentHumidity = NULL;lv_obj_t *ui_pnlCurrentWeather = NULL;lv_obj_t *ui_imgCurrentWeather = NULL;lv_obj_t *ui_btnGoToTimerScreen = NULL;lv_obj_t *ui_pnlForecast = NULL;lv_obj_t *ui_pnlForecastD0 = NULL;lv_obj_t *ui_imgForecastD0 = NULL;lv_obj_t *ui_lblForecastTempD0 = NULL;lv_obj_t *ui_lblForecastDayD0 = NULL;lv_obj_t *ui_pnlForecastD1 = NULL;lv_obj_t *ui_imgForecastD1 = NULL;lv_obj_t *ui_lblForecastTempD1 = NULL;lv_obj_t *ui_lblForecastDayD1 = NULL;lv_obj_t *ui_pnlForecastD2 = NULL;lv_obj_t *ui_imgForecastD2 = NULL;lv_obj_t *ui_lblForecastTempD2 = NULL;lv_obj_t *ui_lblForecastDayD2 = NULL;lv_obj_t *ui_pnlForecastD3 = NULL;lv_obj_t *ui_imgForecastD3 = NULL;lv_obj_t *ui_lblForecastTempD3 = NULL;lv_obj_t *ui_lblForecastDayD3 = NULL;lv_obj_t *ui_pnlForecastD4 = NULL;lv_obj_t *ui_imgForecastD4 = NULL;lv_obj_t *ui_lblForecastTempD4 = NULL;lv_obj_t *ui_lblForecastDayD4 = NULL;lv_obj_t *ui_pnlStatus = NULL;lv_obj_t *ui_pnlGarageDoorStatus = NULL;lv_obj_t *ui_lblGarageDoor = NULL;lv_obj_t *ui_lblGarageDoorStatus = NULL;lv_obj_t *ui_pnlPlaceHolderStatus = NULL;lv_obj_t *ui_lblEvent1 = NULL;lv_obj_t *ui_lblEventStatus1 = NULL;lv_obj_t *ui_pnlCalEvents = NULL;lv_obj_t *ui_txtCalEvents = NULL;lv_obj_t *ui_pnlEnclosure = NULL;lv_obj_t *ui_Label9 = NULL;lv_obj_t *ui_lblEnclosureTemp = NULL;lv_obj_t *ui_lblEnclosureHumidity = NULL;lv_obj_t *ui_pnlIndoor = NULL;lv_obj_t *ui_Label1 = NULL;lv_obj_t *ui_lblIndoorTemp = NULL;lv_obj_t *ui_lblIndoorHumidity = NULL;lv_obj_t *ui_lblTemp = NULL;lv_obj_t *ui_lblHumidity = NULL;lv_obj_t *ui_lblGarageTime = NULL;
// event funtions
void ui_event_btnGoToTimerScreen( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_screentimer, LV_SCR_LOAD_ANIM_MOVE_LEFT, 100, 0, &ui_screentimer_screen_init);
}
}

// build funtions

void ui_screendashboard_screen_init(void)
{
ui_screendashboard = lv_obj_create(NULL);
lv_obj_clear_flag( ui_screendashboard, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_pnlTimeDate = lv_obj_create(ui_screendashboard);
lv_obj_set_width( ui_pnlTimeDate, 217);
lv_obj_set_height( ui_pnlTimeDate, 121);
lv_obj_set_x( ui_pnlTimeDate, -277 );
lv_obj_set_y( ui_pnlTimeDate, -170 );
lv_obj_set_align( ui_pnlTimeDate, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_pnlTimeDate, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_pnlTimeDate, lv_color_hex(0x31314A), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_pnlTimeDate, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lblTimeOfDay = lv_label_create(ui_pnlTimeDate);
lv_obj_set_width( ui_lblTimeOfDay, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_lblTimeOfDay, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_lblTimeOfDay, -1 );
lv_obj_set_y( ui_lblTimeOfDay, -19 );
lv_obj_set_align( ui_lblTimeOfDay, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_lblTimeOfDay,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_lblTimeOfDay, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_label_set_text(ui_lblTimeOfDay,"12:00");
lv_obj_set_style_text_font(ui_lblTimeOfDay, &ui_font_Big_Number, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lblDate = lv_label_create(ui_pnlTimeDate);
lv_obj_set_width( ui_lblDate, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_lblDate, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_lblDate, -1 );
lv_obj_set_y( ui_lblDate, 38 );
lv_obj_set_align( ui_lblDate, LV_ALIGN_CENTER );
lv_label_set_text(ui_lblDate,"Mon, April 14");
lv_obj_set_style_text_font(ui_lblDate, &lv_font_montserrat_28, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_pnlOutsideTemp = lv_obj_create(ui_screendashboard);
lv_obj_set_width( ui_pnlOutsideTemp, 537);
lv_obj_set_height( ui_pnlOutsideTemp, 121);
lv_obj_set_x( ui_pnlOutsideTemp, 113 );
lv_obj_set_y( ui_pnlOutsideTemp, -168 );
lv_obj_set_align( ui_pnlOutsideTemp, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_pnlOutsideTemp, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_pnlOutsideTemp, lv_color_hex(0x4A0E1C), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_pnlOutsideTemp, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_chtTemp = lv_chart_create(ui_pnlOutsideTemp);
lv_obj_set_width( ui_chtTemp, 252);
lv_obj_set_height( ui_chtTemp, 55);
lv_obj_set_x( ui_chtTemp, 136 );
lv_obj_set_y( ui_chtTemp, -27 );
lv_obj_set_align( ui_chtTemp, LV_ALIGN_CENTER );
lv_chart_set_type( ui_chtTemp, LV_CHART_TYPE_LINE);
lv_chart_set_point_count( ui_chtTemp, 20);
lv_chart_set_range( ui_chtTemp, LV_CHART_AXIS_PRIMARY_Y, 20, 110);
lv_chart_set_div_line_count( ui_chtTemp, 0, 0);
lv_chart_set_axis_tick( ui_chtTemp, LV_CHART_AXIS_PRIMARY_X, 0, 0, 0, 0, false, 50);
lv_chart_set_axis_tick( ui_chtTemp, LV_CHART_AXIS_PRIMARY_Y, 0, 0, 2, 2, true, 50);
lv_chart_set_axis_tick( ui_chtTemp, LV_CHART_AXIS_SECONDARY_Y, 0, 0, 0, 0, false, 25);
lv_chart_series_t* ui_chtTemp_series_1 = lv_chart_add_series(ui_chtTemp, lv_color_hex(0xA5ECF5), LV_CHART_AXIS_PRIMARY_Y);
static lv_coord_t ui_chtTemp_series_1_array[] = { 10,15,25,45,65,70,60,50,40,45,50,55,60,65,70,75,80,85,90,95 };
lv_chart_set_ext_y_array(ui_chtTemp, ui_chtTemp_series_1, ui_chtTemp_series_1_array);
lv_obj_set_style_bg_grad_color(ui_chtTemp, lv_color_hex(0x6C8216), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_main_stop(ui_chtTemp, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_stop(ui_chtTemp, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_dir(ui_chtTemp, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_size(ui_chtTemp, 1, LV_PART_INDICATOR| LV_STATE_DEFAULT);

ui_chtHumidity = lv_chart_create(ui_pnlOutsideTemp);
lv_obj_set_width( ui_chtHumidity, 252);
lv_obj_set_height( ui_chtHumidity, 55);
lv_obj_set_x( ui_chtHumidity, 136 );
lv_obj_set_y( ui_chtHumidity, 31 );
lv_obj_set_align( ui_chtHumidity, LV_ALIGN_CENTER );
lv_chart_set_type( ui_chtHumidity, LV_CHART_TYPE_LINE);
lv_chart_set_point_count( ui_chtHumidity, 20);
lv_chart_set_div_line_count( ui_chtHumidity, 0, 0);
lv_chart_set_axis_tick( ui_chtHumidity, LV_CHART_AXIS_PRIMARY_X, 0, 0, 0, 0, false, 50);
lv_chart_set_axis_tick( ui_chtHumidity, LV_CHART_AXIS_PRIMARY_Y, 0, 1, 2, 1, true, 50);
lv_chart_set_axis_tick( ui_chtHumidity, LV_CHART_AXIS_SECONDARY_Y, 0, 0, 0, 0, false, 25);
lv_chart_series_t* ui_chtHumidity_series_1 = lv_chart_add_series(ui_chtHumidity, lv_color_hex(0xA5ECF5), LV_CHART_AXIS_PRIMARY_Y);
static lv_coord_t ui_chtHumidity_series_1_array[] = { 10,15,25,45,65,70,60,50,40,45,50,55,60,65,70,75,80,85,90,95 };
lv_chart_set_ext_y_array(ui_chtHumidity, ui_chtHumidity_series_1, ui_chtHumidity_series_1_array);
lv_obj_set_style_bg_color(ui_chtHumidity, lv_color_hex(0x23EB75), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_chtHumidity, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_chtHumidity, lv_color_hex(0x0C4B26), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_grad_dir(ui_chtHumidity, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_size(ui_chtHumidity, 1, LV_PART_INDICATOR| LV_STATE_DEFAULT);

ui_lblCurrentTemp = lv_label_create(ui_pnlOutsideTemp);
lv_obj_set_width( ui_lblCurrentTemp, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_lblCurrentTemp, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_lblCurrentTemp, -198 );
lv_obj_set_y( ui_lblCurrentTemp, -21 );
lv_obj_set_align( ui_lblCurrentTemp, LV_ALIGN_CENTER );
lv_label_set_text(ui_lblCurrentTemp,"100 F");
lv_obj_set_style_text_font(ui_lblCurrentTemp, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lblCurrentHumidity = lv_label_create(ui_pnlOutsideTemp);
lv_obj_set_width( ui_lblCurrentHumidity, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_lblCurrentHumidity, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_lblCurrentHumidity, -196 );
lv_obj_set_y( ui_lblCurrentHumidity, 27 );
lv_obj_set_align( ui_lblCurrentHumidity, LV_ALIGN_CENTER );
lv_label_set_text(ui_lblCurrentHumidity,"78%");
lv_obj_set_style_text_font(ui_lblCurrentHumidity, &lv_font_montserrat_32, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_pnlCurrentWeather = lv_obj_create(ui_pnlOutsideTemp);
lv_obj_set_width( ui_pnlCurrentWeather, 109);
lv_obj_set_height( ui_pnlCurrentWeather, 112);
lv_obj_set_x( ui_pnlCurrentWeather, -79 );
lv_obj_set_y( ui_pnlCurrentWeather, 2 );
lv_obj_set_align( ui_pnlCurrentWeather, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_pnlCurrentWeather, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_pnlCurrentWeather, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_pnlCurrentWeather, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_imgCurrentWeather = lv_img_create(ui_pnlCurrentWeather);
lv_img_set_src(ui_imgCurrentWeather, &ui_img_snowrainmix_png);
lv_obj_set_width( ui_imgCurrentWeather, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_imgCurrentWeather, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_imgCurrentWeather, 2 );
lv_obj_set_y( ui_imgCurrentWeather, 1 );
lv_obj_set_align( ui_imgCurrentWeather, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_imgCurrentWeather, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_imgCurrentWeather, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_btnGoToTimerScreen = lv_imgbtn_create(ui_screendashboard);
lv_imgbtn_set_src(ui_btnGoToTimerScreen, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_rt_arrow_png, NULL);
lv_imgbtn_set_src(ui_btnGoToTimerScreen, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_rt_arrow_png, NULL);
lv_obj_set_width( ui_btnGoToTimerScreen, 64);
lv_obj_set_height( ui_btnGoToTimerScreen, 64);
lv_obj_set_x( ui_btnGoToTimerScreen, 356 );
lv_obj_set_y( ui_btnGoToTimerScreen, 195 );
lv_obj_set_align( ui_btnGoToTimerScreen, LV_ALIGN_CENTER );
lv_obj_set_style_radius(ui_btnGoToTimerScreen, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_btnGoToTimerScreen, lv_color_hex(0x4D4F5B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_btnGoToTimerScreen, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_color(ui_btnGoToTimerScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_outline_opa(ui_btnGoToTimerScreen, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_pnlForecast = lv_obj_create(ui_screendashboard);
lv_obj_set_width( ui_pnlForecast, 537);
lv_obj_set_height( ui_pnlForecast, 134);
lv_obj_set_x( ui_pnlForecast, 113 );
lv_obj_set_y( ui_pnlForecast, -29 );
lv_obj_set_align( ui_pnlForecast, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_pnlForecast, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_pnlForecast, lv_color_hex(0x033E17), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_pnlForecast, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_pnlForecastD0 = lv_obj_create(ui_pnlForecast);
lv_obj_set_width( ui_pnlForecastD0, 96);
lv_obj_set_height( ui_pnlForecastD0, 119);
lv_obj_set_x( ui_pnlForecastD0, -211 );
lv_obj_set_y( ui_pnlForecastD0, -4 );
lv_obj_set_align( ui_pnlForecastD0, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_pnlForecastD0, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_pnlForecastD0, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_pnlForecastD0, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_imgForecastD0 = lv_img_create(ui_pnlForecastD0);
lv_img_set_src(ui_imgForecastD0, &ui_img_partlycloudy_png);
lv_obj_set_width( ui_imgForecastD0, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_imgForecastD0, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_imgForecastD0, 2 );
lv_obj_set_y( ui_imgForecastD0, -2 );
lv_obj_set_align( ui_imgForecastD0, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_imgForecastD0, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_imgForecastD0, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_imgForecastD0,165);

ui_lblForecastTempD0 = lv_label_create(ui_pnlForecastD0);
lv_obj_set_width( ui_lblForecastTempD0, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_lblForecastTempD0, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_lblForecastTempD0, 1 );
lv_obj_set_y( ui_lblForecastTempD0, 45 );
lv_obj_set_align( ui_lblForecastTempD0, LV_ALIGN_CENTER );
lv_label_set_text(ui_lblForecastTempD0,"100  |  100");
lv_obj_set_style_text_font(ui_lblForecastTempD0, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lblForecastDayD0 = lv_label_create(ui_pnlForecastD0);
lv_obj_set_width( ui_lblForecastDayD0, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_lblForecastDayD0, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_lblForecastDayD0, -1 );
lv_obj_set_y( ui_lblForecastDayD0, -45 );
lv_obj_set_align( ui_lblForecastDayD0, LV_ALIGN_CENTER );
lv_label_set_text(ui_lblForecastDayD0,"Today");

ui_pnlForecastD1 = lv_obj_create(ui_pnlForecast);
lv_obj_set_width( ui_pnlForecastD1, 96);
lv_obj_set_height( ui_pnlForecastD1, 119);
lv_obj_set_x( ui_pnlForecastD1, -106 );
lv_obj_set_y( ui_pnlForecastD1, -4 );
lv_obj_set_align( ui_pnlForecastD1, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_pnlForecastD1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_pnlForecastD1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_pnlForecastD1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_imgForecastD1 = lv_img_create(ui_pnlForecastD1);
lv_img_set_src(ui_imgForecastD1, &ui_img_heavyrain_png);
lv_obj_set_width( ui_imgForecastD1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_imgForecastD1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_imgForecastD1, 2 );
lv_obj_set_y( ui_imgForecastD1, -2 );
lv_obj_set_align( ui_imgForecastD1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_imgForecastD1, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_imgForecastD1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_imgForecastD1,165);

ui_lblForecastTempD1 = lv_label_create(ui_pnlForecastD1);
lv_obj_set_width( ui_lblForecastTempD1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_lblForecastTempD1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_lblForecastTempD1, 1 );
lv_obj_set_y( ui_lblForecastTempD1, 45 );
lv_obj_set_align( ui_lblForecastTempD1, LV_ALIGN_CENTER );
lv_label_set_text(ui_lblForecastTempD1,"100  |  100");
lv_obj_set_style_text_font(ui_lblForecastTempD1, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lblForecastDayD1 = lv_label_create(ui_pnlForecastD1);
lv_obj_set_width( ui_lblForecastDayD1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_lblForecastDayD1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_lblForecastDayD1, -1 );
lv_obj_set_y( ui_lblForecastDayD1, -45 );
lv_obj_set_align( ui_lblForecastDayD1, LV_ALIGN_CENTER );
lv_label_set_text(ui_lblForecastDayD1,"Today");

ui_pnlForecastD2 = lv_obj_create(ui_pnlForecast);
lv_obj_set_width( ui_pnlForecastD2, 96);
lv_obj_set_height( ui_pnlForecastD2, 119);
lv_obj_set_x( ui_pnlForecastD2, -1 );
lv_obj_set_y( ui_pnlForecastD2, -4 );
lv_obj_set_align( ui_pnlForecastD2, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_pnlForecastD2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_pnlForecastD2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_pnlForecastD2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_imgForecastD2 = lv_img_create(ui_pnlForecastD2);
lv_img_set_src(ui_imgForecastD2, &ui_img_sunnyday_png);
lv_obj_set_width( ui_imgForecastD2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_imgForecastD2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_imgForecastD2, 2 );
lv_obj_set_y( ui_imgForecastD2, -2 );
lv_obj_set_align( ui_imgForecastD2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_imgForecastD2, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_imgForecastD2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_imgForecastD2,165);

ui_lblForecastTempD2 = lv_label_create(ui_pnlForecastD2);
lv_obj_set_width( ui_lblForecastTempD2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_lblForecastTempD2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_lblForecastTempD2, 1 );
lv_obj_set_y( ui_lblForecastTempD2, 45 );
lv_obj_set_align( ui_lblForecastTempD2, LV_ALIGN_CENTER );
lv_label_set_text(ui_lblForecastTempD2,"100  |  100");
lv_obj_set_style_text_font(ui_lblForecastTempD2, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lblForecastDayD2 = lv_label_create(ui_pnlForecastD2);
lv_obj_set_width( ui_lblForecastDayD2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_lblForecastDayD2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_lblForecastDayD2, -1 );
lv_obj_set_y( ui_lblForecastDayD2, -45 );
lv_obj_set_align( ui_lblForecastDayD2, LV_ALIGN_CENTER );
lv_label_set_text(ui_lblForecastDayD2,"Today");

ui_pnlForecastD3 = lv_obj_create(ui_pnlForecast);
lv_obj_set_width( ui_pnlForecastD3, 96);
lv_obj_set_height( ui_pnlForecastD3, 119);
lv_obj_set_x( ui_pnlForecastD3, 101 );
lv_obj_set_y( ui_pnlForecastD3, -4 );
lv_obj_set_align( ui_pnlForecastD3, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_pnlForecastD3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_pnlForecastD3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_pnlForecastD3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_imgForecastD3 = lv_img_create(ui_pnlForecastD3);
lv_img_set_src(ui_imgForecastD3, &ui_img_partlycloudy_png);
lv_obj_set_width( ui_imgForecastD3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_imgForecastD3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_imgForecastD3, 2 );
lv_obj_set_y( ui_imgForecastD3, -2 );
lv_obj_set_align( ui_imgForecastD3, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_imgForecastD3, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_imgForecastD3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_imgForecastD3,165);

ui_lblForecastTempD3 = lv_label_create(ui_pnlForecastD3);
lv_obj_set_width( ui_lblForecastTempD3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_lblForecastTempD3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_lblForecastTempD3, 1 );
lv_obj_set_y( ui_lblForecastTempD3, 45 );
lv_obj_set_align( ui_lblForecastTempD3, LV_ALIGN_CENTER );
lv_label_set_text(ui_lblForecastTempD3,"100  |  100");
lv_obj_set_style_text_font(ui_lblForecastTempD3, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lblForecastDayD3 = lv_label_create(ui_pnlForecastD3);
lv_obj_set_width( ui_lblForecastDayD3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_lblForecastDayD3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_lblForecastDayD3, -1 );
lv_obj_set_y( ui_lblForecastDayD3, -45 );
lv_obj_set_align( ui_lblForecastDayD3, LV_ALIGN_CENTER );
lv_label_set_text(ui_lblForecastDayD3,"Today");

ui_pnlForecastD4 = lv_obj_create(ui_pnlForecast);
lv_obj_set_width( ui_pnlForecastD4, 96);
lv_obj_set_height( ui_pnlForecastD4, 119);
lv_obj_set_x( ui_pnlForecastD4, 203 );
lv_obj_set_y( ui_pnlForecastD4, -4 );
lv_obj_set_align( ui_pnlForecastD4, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_pnlForecastD4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_pnlForecastD4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_pnlForecastD4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_imgForecastD4 = lv_img_create(ui_pnlForecastD4);
lv_img_set_src(ui_imgForecastD4, &ui_img_thunderstorms_png);
lv_obj_set_width( ui_imgForecastD4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_imgForecastD4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_imgForecastD4, 2 );
lv_obj_set_y( ui_imgForecastD4, -2 );
lv_obj_set_align( ui_imgForecastD4, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_imgForecastD4, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_imgForecastD4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_imgForecastD4,165);

ui_lblForecastTempD4 = lv_label_create(ui_pnlForecastD4);
lv_obj_set_width( ui_lblForecastTempD4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_lblForecastTempD4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_lblForecastTempD4, 1 );
lv_obj_set_y( ui_lblForecastTempD4, 45 );
lv_obj_set_align( ui_lblForecastTempD4, LV_ALIGN_CENTER );
lv_label_set_text(ui_lblForecastTempD4,"100  |  100");
lv_obj_set_style_text_font(ui_lblForecastTempD4, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lblForecastDayD4 = lv_label_create(ui_pnlForecastD4);
lv_obj_set_width( ui_lblForecastDayD4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_lblForecastDayD4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_lblForecastDayD4, -1 );
lv_obj_set_y( ui_lblForecastDayD4, -45 );
lv_obj_set_align( ui_lblForecastDayD4, LV_ALIGN_CENTER );
lv_label_set_text(ui_lblForecastDayD4,"Today");

ui_pnlStatus = lv_obj_create(ui_screendashboard);
lv_obj_set_width( ui_pnlStatus, 217);
lv_obj_set_height( ui_pnlStatus, 320);
lv_obj_set_x( ui_pnlStatus, -277 );
lv_obj_set_y( ui_pnlStatus, 65 );
lv_obj_set_align( ui_pnlStatus, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_pnlStatus, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_pnlGarageDoorStatus = lv_obj_create(ui_pnlStatus);
lv_obj_set_width( ui_pnlGarageDoorStatus, 190);
lv_obj_set_height( ui_pnlGarageDoorStatus, 83);
lv_obj_set_x( ui_pnlGarageDoorStatus, 0 );
lv_obj_set_y( ui_pnlGarageDoorStatus, -101 );
lv_obj_set_align( ui_pnlGarageDoorStatus, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_pnlGarageDoorStatus, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_pnlGarageDoorStatus, lv_color_hex(0x1D254A), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_pnlGarageDoorStatus, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lblGarageDoor = lv_label_create(ui_pnlGarageDoorStatus);
lv_obj_set_width( ui_lblGarageDoor, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_lblGarageDoor, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_lblGarageDoor, 0 );
lv_obj_set_y( ui_lblGarageDoor, -24 );
lv_obj_set_align( ui_lblGarageDoor, LV_ALIGN_CENTER );
lv_label_set_text(ui_lblGarageDoor,"Garage Door");
lv_obj_set_style_text_font(ui_lblGarageDoor, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lblGarageDoorStatus = lv_label_create(ui_pnlGarageDoorStatus);
lv_obj_set_width( ui_lblGarageDoorStatus, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_lblGarageDoorStatus, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_lblGarageDoorStatus, 0 );
lv_obj_set_y( ui_lblGarageDoorStatus, 5 );
lv_obj_set_align( ui_lblGarageDoorStatus, LV_ALIGN_CENTER );
lv_label_set_text(ui_lblGarageDoorStatus,"Closed");
lv_obj_set_style_text_font(ui_lblGarageDoorStatus, &lv_font_montserrat_28, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_pnlPlaceHolderStatus = lv_obj_create(ui_pnlStatus);
lv_obj_set_width( ui_pnlPlaceHolderStatus, 190);
lv_obj_set_height( ui_pnlPlaceHolderStatus, 82);
lv_obj_set_x( ui_pnlPlaceHolderStatus, 1 );
lv_obj_set_y( ui_pnlPlaceHolderStatus, 43 );
lv_obj_set_align( ui_pnlPlaceHolderStatus, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_pnlPlaceHolderStatus, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_pnlPlaceHolderStatus, lv_color_hex(0x1D254A), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_pnlPlaceHolderStatus, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lblEvent1 = lv_label_create(ui_pnlPlaceHolderStatus);
lv_obj_set_width( ui_lblEvent1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_lblEvent1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_lblEvent1, 0 );
lv_obj_set_y( ui_lblEvent1, -15 );
lv_obj_set_align( ui_lblEvent1, LV_ALIGN_CENTER );
lv_label_set_text(ui_lblEvent1,"Cat Food");
lv_obj_set_style_text_font(ui_lblEvent1, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lblEventStatus1 = lv_label_create(ui_pnlPlaceHolderStatus);
lv_obj_set_width( ui_lblEventStatus1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_lblEventStatus1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_lblEventStatus1, 0 );
lv_obj_set_y( ui_lblEventStatus1, 19 );
lv_obj_set_align( ui_lblEventStatus1, LV_ALIGN_CENTER );
lv_label_set_text(ui_lblEventStatus1,"Plenty");
lv_obj_set_style_text_font(ui_lblEventStatus1, &lv_font_montserrat_28, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_pnlCalEvents = lv_obj_create(ui_screendashboard);
lv_obj_set_width( ui_pnlCalEvents, 462);
lv_obj_set_height( ui_pnlCalEvents, 178);
lv_obj_set_x( ui_pnlCalEvents, 78 );
lv_obj_set_y( ui_pnlCalEvents, 137 );
lv_obj_set_align( ui_pnlCalEvents, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_pnlCalEvents, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_txtCalEvents = lv_textarea_create(ui_pnlCalEvents);
lv_obj_set_width( ui_txtCalEvents, 472);
lv_obj_set_height( ui_txtCalEvents, LV_SIZE_CONTENT);   /// 210
lv_obj_set_x( ui_txtCalEvents, 0 );
lv_obj_set_y( ui_txtCalEvents, -13 );
lv_obj_set_align( ui_txtCalEvents, LV_ALIGN_CENTER );
lv_textarea_set_text(ui_txtCalEvents,"012345678901234567890123456789012345678901234567890123456789012\n[1d] Tom - Dentist\n");
lv_obj_set_style_text_color(ui_txtCalEvents, lv_color_hex(0xB4E4F7), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_txtCalEvents, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_txtCalEvents, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_txtCalEvents, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_pnlEnclosure = lv_obj_create(ui_screendashboard);
lv_obj_set_width( ui_pnlEnclosure, 75);
lv_obj_set_height( ui_pnlEnclosure, 47);
lv_obj_set_x( ui_pnlEnclosure, 356 );
lv_obj_set_y( ui_pnlEnclosure, 73 );
lv_obj_set_align( ui_pnlEnclosure, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_pnlEnclosure, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label9 = lv_label_create(ui_pnlEnclosure);
lv_obj_set_width( ui_Label9, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label9, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label9, 0 );
lv_obj_set_y( ui_Label9, -11 );
lv_obj_set_align( ui_Label9, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label9,"Enclosure");
lv_obj_set_style_text_color(ui_Label9, lv_color_hex(0xAEA9A9), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label9, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label9, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lblEnclosureTemp = lv_label_create(ui_pnlEnclosure);
lv_obj_set_width( ui_lblEnclosureTemp, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_lblEnclosureTemp, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_lblEnclosureTemp, -15 );
lv_obj_set_y( ui_lblEnclosureTemp, 8 );
lv_obj_set_align( ui_lblEnclosureTemp, LV_ALIGN_CENTER );
lv_label_set_text(ui_lblEnclosureTemp,"88 F");
lv_obj_set_style_text_color(ui_lblEnclosureTemp, lv_color_hex(0xAEA9A9), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_lblEnclosureTemp, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_lblEnclosureTemp, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lblEnclosureHumidity = lv_label_create(ui_pnlEnclosure);
lv_obj_set_width( ui_lblEnclosureHumidity, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_lblEnclosureHumidity, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_lblEnclosureHumidity, 20 );
lv_obj_set_y( ui_lblEnclosureHumidity, 8 );
lv_obj_set_align( ui_lblEnclosureHumidity, LV_ALIGN_CENTER );
lv_label_set_text(ui_lblEnclosureHumidity,"65%");
lv_obj_set_style_text_color(ui_lblEnclosureHumidity, lv_color_hex(0xAEA9A9), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_lblEnclosureHumidity, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_lblEnclosureHumidity, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_pnlIndoor = lv_obj_create(ui_screendashboard);
lv_obj_set_width( ui_pnlIndoor, 75);
lv_obj_set_height( ui_pnlIndoor, 47);
lv_obj_set_x( ui_pnlIndoor, 357 );
lv_obj_set_y( ui_pnlIndoor, 127 );
lv_obj_set_align( ui_pnlIndoor, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_pnlIndoor, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label1 = lv_label_create(ui_pnlIndoor);
lv_obj_set_width( ui_Label1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label1, 0 );
lv_obj_set_y( ui_Label1, -11 );
lv_obj_set_align( ui_Label1, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label1,"Indoor");
lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0xAEA9A9), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lblIndoorTemp = lv_label_create(ui_pnlIndoor);
lv_obj_set_width( ui_lblIndoorTemp, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_lblIndoorTemp, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_lblIndoorTemp, -15 );
lv_obj_set_y( ui_lblIndoorTemp, 8 );
lv_obj_set_align( ui_lblIndoorTemp, LV_ALIGN_CENTER );
lv_label_set_text(ui_lblIndoorTemp,"88 F");
lv_obj_set_style_text_color(ui_lblIndoorTemp, lv_color_hex(0xAEA9A9), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_lblIndoorTemp, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_lblIndoorTemp, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lblIndoorHumidity = lv_label_create(ui_pnlIndoor);
lv_obj_set_width( ui_lblIndoorHumidity, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_lblIndoorHumidity, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_lblIndoorHumidity, 20 );
lv_obj_set_y( ui_lblIndoorHumidity, 8 );
lv_obj_set_align( ui_lblIndoorHumidity, LV_ALIGN_CENTER );
lv_label_set_text(ui_lblIndoorHumidity,"65%");
lv_obj_set_style_text_color(ui_lblIndoorHumidity, lv_color_hex(0xAEA9A9), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_lblIndoorHumidity, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_lblIndoorHumidity, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lblTemp = lv_label_create(ui_screendashboard);
lv_obj_set_width( ui_lblTemp, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_lblTemp, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_lblTemp, 144 );
lv_obj_set_y( ui_lblTemp, -213 );
lv_obj_set_align( ui_lblTemp, LV_ALIGN_CENTER );
lv_label_set_text(ui_lblTemp,"Temp");
lv_obj_set_style_text_color(ui_lblTemp, lv_color_hex(0xACF5F4), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_lblTemp, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_lblTemp, &lv_font_montserrat_10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lblHumidity = lv_label_create(ui_screendashboard);
lv_obj_set_width( ui_lblHumidity, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_lblHumidity, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_lblHumidity, 152 );
lv_obj_set_y( ui_lblHumidity, -157 );
lv_obj_set_align( ui_lblHumidity, LV_ALIGN_CENTER );
lv_label_set_text(ui_lblHumidity,"Humidify");
lv_obj_set_style_text_color(ui_lblHumidity, lv_color_hex(0x852CA3), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_lblHumidity, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_lblHumidity, &lv_font_montserrat_10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lblGarageTime = lv_label_create(ui_screendashboard);
lv_obj_set_width( ui_lblGarageTime, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_lblGarageTime, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_lblGarageTime, -278 );
lv_obj_set_y( ui_lblGarageTime, -8 );
lv_obj_set_align( ui_lblGarageTime, LV_ALIGN_CENTER );
lv_label_set_text(ui_lblGarageTime,"4/05/26 - 12:34p");
lv_obj_set_style_text_font(ui_lblGarageTime, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_btnGoToTimerScreen, ui_event_btnGoToTimerScreen, LV_EVENT_ALL, NULL);

}

void ui_screendashboard_screen_destroy(void)
{
   if (ui_screendashboard) lv_obj_del(ui_screendashboard);

// NULL screen variables
ui_screendashboard= NULL;
ui_pnlTimeDate= NULL;
ui_lblTimeOfDay= NULL;
ui_lblDate= NULL;
ui_pnlOutsideTemp= NULL;
ui_chtTemp= NULL;
ui_chtHumidity= NULL;
ui_lblCurrentTemp= NULL;
ui_lblCurrentHumidity= NULL;
ui_pnlCurrentWeather= NULL;
ui_imgCurrentWeather= NULL;
ui_btnGoToTimerScreen= NULL;
ui_pnlForecast= NULL;
ui_pnlForecastD0= NULL;
ui_imgForecastD0= NULL;
ui_lblForecastTempD0= NULL;
ui_lblForecastDayD0= NULL;
ui_pnlForecastD1= NULL;
ui_imgForecastD1= NULL;
ui_lblForecastTempD1= NULL;
ui_lblForecastDayD1= NULL;
ui_pnlForecastD2= NULL;
ui_imgForecastD2= NULL;
ui_lblForecastTempD2= NULL;
ui_lblForecastDayD2= NULL;
ui_pnlForecastD3= NULL;
ui_imgForecastD3= NULL;
ui_lblForecastTempD3= NULL;
ui_lblForecastDayD3= NULL;
ui_pnlForecastD4= NULL;
ui_imgForecastD4= NULL;
ui_lblForecastTempD4= NULL;
ui_lblForecastDayD4= NULL;
ui_pnlStatus= NULL;
ui_pnlGarageDoorStatus= NULL;
ui_lblGarageDoor= NULL;
ui_lblGarageDoorStatus= NULL;
ui_pnlPlaceHolderStatus= NULL;
ui_lblEvent1= NULL;
ui_lblEventStatus1= NULL;
ui_pnlCalEvents= NULL;
ui_txtCalEvents= NULL;
ui_pnlEnclosure= NULL;
ui_Label9= NULL;
ui_lblEnclosureTemp= NULL;
ui_lblEnclosureHumidity= NULL;
ui_pnlIndoor= NULL;
ui_Label1= NULL;
ui_lblIndoorTemp= NULL;
ui_lblIndoorHumidity= NULL;
ui_lblTemp= NULL;
ui_lblHumidity= NULL;
ui_lblGarageTime= NULL;

}
