; PlatformIO Project Configuration File
; CrowPanel Display Node - ESP32-S3 7.0" HMI with MQTT + LVGL

[platformio]
src_dir = src
boards_dir = .

[env:esp32-s3-devkitc-1-myboard]
platform = espressif32
board = esp32-s3-devkitc-1-myboard
framework = arduino
platform_packages = framework-arduinoespressif32 @ https://github.com/espressif/arduino-esp32#2.0.3
build_flags =
    -D LV_LVGL_H_INCLUDE_SIMPLE
    -D LV_CONF_SKIP
    -D LV_COLOR_DEPTH=16
    -D LV_MEM_SIZE=65536
    -D LV_DISP_DEF_REFR_PERIOD=30
    -D LV_FONT_MONTSERRAT_10=1
    -D LV_FONT_MONTSERRAT_12=1
    -D LV_FONT_MONTSERRAT_14=1
    -D LV_FONT_MONTSERRAT_20=1
    -D LV_FONT_MONTSERRAT_28=1
    -D LV_FONT_MONTSERRAT_48=1
    -I./include
    -I../common/include
    -I${sysenv.HOME}/.sierra
lib_deps =
    lvgl/lvgl@8.3.6
    tamctec/TAMC_GT911@^1.0.2
    lovyan03/LovyanGFX@^1.1.12
    knolleary/PubSubClient@^2.8
    bblanchon/ArduinoJson@^6.21.0
board_build.partitions = huge_app.csv
upload_speed = 115200
monitor_speed = 9600
